spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:54321/db
        username: postgres
        password: 123
        initialization-mode: never
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
